[preset 0]
no_display

[preset 1]
### CPU
table_columns=3
cpu_stats
cpu_mhz
cpu_temp
cpu_power

### GPU
gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_temp
gpu_power
vram

### RAM
# swap
ram

[preset 2]
table_columns=6
### CPU
cpu_stats
cpu_mhz
cpu_temp
cpu_power
core_load

# core_bars
# table_columns=3

### GPU
gpu_stats
gpu_core_clock
gpu_mem_clock
gpu_temp
gpu_power
vram
